name: Tests CI

on: [push, pull_request]

jobs:
  "Run-Tests":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.x
          cache: npm
      - run: npm ci
      - run: npm run test-ci
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: junit.xml
          reporter: jest-junit